export const VISUAL_STYLES = [
  { id: "ink-brush-documentary", title: "Ink Brush Documentary", description: "Bold ink strokes on parchment, brush wipe transitions", emoji: "🖌️", categories: ["Documentary", "Historical", "Art"] },
  { id: "vintage-map-documentary", title: "Vintage Map Documentary", description: "Sepia cartographic render, aged scroll aesthetic", emoji: "🗺️", categories: ["Documentary", "Historical"] },
  { id: "cinematic-3d-render", title: "Cinematic 3D Render", description: "Hyper-realistic 3D grayscale with soft cinematic lighting", emoji: "🎬", categories: ["All", "Cinematic"] },
  { id: "archival-bw", title: "Archival Black & White", description: "Film grain, 1940s archival footage look", emoji: "📽️", categories: ["Historical", "Documentary"] },
  { id: "found-footage", title: "Found Footage", description: "Raw handheld camera, VHS degradation artifacts", emoji: "📹", categories: ["Cinematic", "Raw"] },
  { id: "nature-wildlife", title: "Nature Wildlife", description: "Lush golden-hour saturation, wildlife lens blur", emoji: "🦁", categories: ["Nature", "Documentary"] },
  { id: "space-cosmos", title: "Space & Cosmos", description: "Deep space nebula tones, dark cosmic atmosphere", emoji: "🌌", categories: ["Sci-Fi / Tech", "Nature"] },
  { id: "true-crime-dark", title: "True Crime Dark", description: "Moody shadows, red string board, crime scene aesthetic", emoji: "🔍", categories: ["Psychology", "Documentary"] },
  { id: "history-explainer-25d", title: "History Explainer 2.5D", description: "AI-rendered historical scenes with Ken Burns motion", emoji: "🏛️", categories: ["Historical", "Documentary"] },
  { id: "political-propaganda", title: "Political Propaganda Poster", description: "Bold screen-print colors, vintage poster typography", emoji: "✊", categories: ["Historical", "Art"] },
  { id: "historical-newspaper", title: "Historical Newspaper Cutout", description: "Aged newsprint texture, headline typography, ink bleed", emoji: "📰", categories: ["Historical", "Documentary"] },
  { id: "cold-war-archive", title: "Cold War Archive Footage", description: "Grainy 16mm film, faded Kodachrome, era-specific tension", emoji: "🎞️", categories: ["Historical", "Documentary"] },
  { id: "ancient-scroll", title: "Ancient Scroll Illustration", description: "Hand-painted papyrus scroll, ancient ink illustrations", emoji: "📖", categories: ["Historical", "Art"] },
  { id: "dark-history-engraving", title: "Dark History Engraving", description: "Steel engraving cross-hatching, dramatic chiaroscuro", emoji: "⚔️", categories: ["Historical", "Art"] },
  { id: "roman-empire-painting", title: "Roman Empire Painting", description: "Fresco-style marble columns, classical Roman palette", emoji: "🏟️", categories: ["Historical", "Art"] },
  { id: "renaissance-documentary", title: "Renaissance Documentary", description: "Oil painting depth, golden ratio compositions, sfumato", emoji: "🖼️", categories: ["Historical", "Art"] },
  { id: "tactical-briefing", title: "Tactical Briefing", description: "Mission map overlay, strategic stencil type, sepia tones", emoji: "🪖", categories: ["Historical", "Documentary"] },
  { id: "crime-investigation-board", title: "Crime Investigation Board", description: "Evidence board with red string, polaroids, case file look", emoji: "🔎", categories: ["Psychology", "Documentary"] },
  { id: "detective-case-file", title: "Detective Case File", description: "Manila folder aesthetic, typewriter font, stamped evidence", emoji: "🗂️", categories: ["Psychology", "Documentary"] },
  { id: "watercolor-motivation", title: "Watercolor Motivation", description: "Soft flowing watercolor washes, pastel bloom transitions", emoji: "💧", categories: ["Motivation", "Art"] },
  { id: "japanese-sumi-e", title: "Japanese Sumi-e", description: "Black ink on rice paper, meditative brush sweep", emoji: "⛩️", categories: ["Art", "Lifestyle"] },
  { id: "neon-wireframe", title: "Neon Wireframe Holograms", description: "Glowing neon on dark background, electric dissolve", emoji: "💡", categories: ["Sci-Fi / Tech"] },
  { id: "gold-black-luxury", title: "Gold & Black Luxury", description: "Rich gold foil on matte black, premium feel", emoji: "👑", categories: ["Lifestyle", "Motivation"] },
  { id: "cosmic-galaxy-motivation", title: "Cosmic Galaxy Motivation", description: "Vibrant nebula colors, floating star particle field", emoji: "✨", categories: ["Motivation", "Sci-Fi / Tech"] },
  { id: "minimalist-typography", title: "Minimalist White Typography", description: "Clean white background, bold kinetic text animation", emoji: "⬜", categories: ["Motivation", "Lifestyle"] },
  { id: "fire-power", title: "Fire & Power", description: "Orange-red embers, dramatic dark background energy", emoji: "🔥", categories: ["Motivation"] },
  { id: "zen-sand-garden", title: "Zen Sand Garden", description: "Raked sand texture, calm minimalist beige tones", emoji: "🧘", categories: ["Lifestyle", "Psychology"] },
  { id: "3d-neon-floating", title: "3D Neon Floating Text", description: "Extruded neon 3D lettering, cinematic depth of field", emoji: "🌟", categories: ["Motivation", "Cinematic"] },
  { id: "chalk-blackboard", title: "Chalk Blackboard", description: "Chalk-drawn figures on blackboard, hand-animated", emoji: "🖊️", categories: ["Animation", "Kids"] },
  { id: "cinematic-golden-hour", title: "Cinematic Golden Hour", description: "Warm lens flare, silhouette hero shots, triumph palette", emoji: "🌇", categories: ["Motivation", "Cinematic"] },
  { id: "epic-success-journey", title: "Epic Success Journey", description: "Montage of rising action, peak moments, soaring score", emoji: "🏆", categories: ["Motivation"] },
  { id: "luxury-lifestyle", title: "Luxury Lifestyle Visuals", description: "Premium brand aesthetics, glossy surfaces, aspirational tones", emoji: "💎", categories: ["Lifestyle", "Motivation"] },
  { id: "corporate-success", title: "Corporate Success Animation", description: "Clean motion graphics, upward trajectories, professional palette", emoji: "📈", categories: ["Motivation", "Lifestyle"] },
  { id: "dream-achievement", title: "Dream Achievement Visuals", description: "Dreamy particle effects, floating aspirational imagery", emoji: "🌙", categories: ["Motivation", "Psychology"] },
  { id: "futuristic-success", title: "Futuristic Success Vision", description: "Sleek futurism, metallic surfaces, bold forward-moving energy", emoji: "🚀", categories: ["Motivation", "Sci-Fi / Tech"] },
  { id: "high-performance", title: "High Performance Athlete Style", description: "Slow-motion sweat drops, stadium lighting, peak effort", emoji: "⚡", categories: ["Motivation", "Lifestyle"] },
  { id: "business-growth", title: "Business Growth Infographic", description: "Animated charts, clean icons, data-driven corporate motion", emoji: "💹", categories: ["Motivation", "Lifestyle"] },
  { id: "vision-board", title: "Vision Board Aesthetic", description: "Magazine cutout collage, handwritten goals, warm tones", emoji: "🎯", categories: ["Motivation", "Psychology"] },
  { id: "stick-figure-depression", title: "Stick Figure Depression", description: "Rough scratchy pencil on white, raw psychological realism", emoji: "🧠", categories: ["Psychology", "Animation"] },
  { id: "glitch-art-anxiety", title: "Glitch Art Anxiety", description: "RGB split, digital noise, fragmented visual reality", emoji: "📡", categories: ["Psychology", "Sci-Fi / Tech"] },
  { id: "dark-watercolor-trauma", title: "Dark Watercolor Trauma", description: "Bleeding dark watercolor, rain-soaked melancholic tones", emoji: "🌧️", categories: ["Psychology", "Art"] },
  { id: "surreal-dream-logic", title: "Surreal Dream Logic", description: "Dalí-style impossible perspectives, dream imagery", emoji: "🌀", categories: ["Psychology", "Art"] },
  { id: "clinical-white-therapy", title: "Clinical White Therapy", description: "Sterile white space, data overlays, therapy aesthetic", emoji: "🏥", categories: ["Psychology", "Lifestyle"] },
  { id: "expressionist-paint", title: "Expressionist Paint", description: "Thick impasto emotion, Munch-style distorted realism", emoji: "🎨", categories: ["Psychology", "Art"] },
  { id: "lonely-silhouette", title: "Lonely Silhouette Art", description: "Single figure in vast empty space, long shadow isolation", emoji: "🕯️", categories: ["Psychology", "Art"] },
  { id: "emotional-sketchbook", title: "Emotional Sketchbook", description: "Messy notebook sketches, tear-smudged ink, raw expression", emoji: "📓", categories: ["Psychology", "Art"] },
  { id: "anxiety-visualization", title: "Anxiety Visualization", description: "Spiraling overlapping lines, erratic motion, overwhelm shapes", emoji: "💭", categories: ["Psychology", "Animation"] },
  { id: "dark-room-psychology", title: "Dark Room Psychology", description: "Single light source in darkness, noir psychological shadows", emoji: "🌑", categories: ["Psychology", "Cinematic"] },
  { id: "inner-mind-landscape", title: "Inner Mind Landscape", description: "Surreal interior mindscape, floating memory fragments", emoji: "🧩", categories: ["Psychology", "Art"] },
  { id: "mental-battle", title: "Mental Battle Animation", description: "Split-screen internal conflict, mirrored dual-self imagery", emoji: "⚔️", categories: ["Psychology", "Animation"] },
  { id: "depression-journal", title: "Depression Journal Style", description: "Sparse diary pages, crossed-out words, heavy emptiness", emoji: "📔", categories: ["Psychology", "Art"] },
  { id: "emotional-watercolor", title: "Emotional Watercolor Portrait", description: "Close-up face in bleeding watercolor, raw emotion portrait", emoji: "🖼️", categories: ["Psychology", "Art"] },
  { id: "shadow-self", title: "Shadow Self Illustration", description: "Jungian shadow double, dark mirror, Rorschach forms", emoji: "👤", categories: ["Psychology", "Art"] },
  { id: "human-brain", title: "Human Brain Visualization", description: "Neural pathways lit up, synapse firing animation, MRI aesthetic", emoji: "🧬", categories: ["Psychology", "Sci-Fi / Tech"] },
  { id: "japanese-manga", title: "Japanese Manga", description: "High-contrast screentone, panel slice transitions", emoji: "⚡", categories: ["Animation", "Art"] },
  { id: "papercraft-stop-motion", title: "Papercraft Stop-Motion", description: "Layered cut-paper, bright primary palette, slide-in", emoji: "📦", categories: ["Animation", "Kids"] },
  { id: "pencil-stick-figure", title: "Pencil Stick Figure", description: "Hand-drawn pencil on paper, sketch reveal animation", emoji: "✏️", categories: ["Animation", "Kids"] },
  { id: "chibi-anime", title: "Chibi Anime Comedy", description: "Super-deformed chibi style, big eyes, comedic timing", emoji: "🐱", categories: ["Animation", "Kids"] }
];

export const CATEGORIES = [
  "All", "Documentary", "Motivation", "Psychology", "Animation", "Kids", 
  "Sci-Fi / Tech", "Lifestyle", "Historical", "Nature", "Art", "Cinematic", "Raw"
];
