import { ProviderTemplate } from './types';

export const communityTemplates: ProviderTemplate[] = [
  {
    templateId: 'nebius',
    name: 'Nebius AI',
    category: 'community',
    description: 'High performance NVIDIA GPU cloud for LLM inference',
    apiBaseUrl: 'https://api.studio.nebius.ai/v1/',
    websiteUrl: 'https://nebius.ai',
    docsUrl: 'https://docs.nebius.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama/Meta-Llama-3.1-70B-Instruct']
  },
  {
    templateId: 'replicate',
    name: 'Replicate',
    category: 'community',
    description: 'Run open-source models with a cloud API',
    apiBaseUrl: 'https://api.replicate.com/v1',
    websiteUrl: 'https://replicate.com',
    docsUrl: 'https://replicate.com/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta/meta-llama-3-70b-instruct']
  },
  {
    templateId: 'baseten',
    name: 'Baseten',
    category: 'community',
    description: 'Fast, scalable AI model deployment',
    apiBaseUrl: 'https://model-{model_id}.api.baseten.co/environments/production',
    websiteUrl: 'https://baseten.co',
    docsUrl: 'https://docs.baseten.co',
    authType: 'custom-header',
    customHeaderName: 'Authorization',
    requiresApiKey: true,
    defaultModels: ['custom-deployment']
  },
  {
    templateId: 'octoai',
    name: 'OctoAI',
    category: 'community',
    description: 'Efficient inference for GenAI',
    apiBaseUrl: 'https://text.octoai.run/v1',
    websiteUrl: 'https://octo.ai',
    docsUrl: 'https://octo.ai/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['llama-2-70b-chat']
  },
  {
    templateId: 'anyscale',
    name: 'Anyscale',
    category: 'community',
    description: 'Endpoints for Llama 3 and Mistral',
    apiBaseUrl: 'https://api.endpoints.anyscale.com/v1',
    websiteUrl: 'https://anyscale.com',
    docsUrl: 'https://docs.endpoints.anyscale.com',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama/Llama-3-70b-chat-hf']
  },
  {
    templateId: 'modal',
    name: 'Modal',
    category: 'community',
    description: 'Serverless GPU computing platform',
    apiBaseUrl: 'https://api.modal.com/v1',
    websiteUrl: 'https://modal.com',
    docsUrl: 'https://modal.com/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['modal-custom-endpoint']
  },
  {
    templateId: 'lepton',
    name: 'Lepton AI',
    category: 'community',
    description: 'Fast and reliable AI platform',
    apiBaseUrl: 'https://api.lepton.ai/v1',
    websiteUrl: 'https://lepton.ai',
    docsUrl: 'https://www.lepton.ai/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['llama3-70b']
  },
  {
    templateId: 'featherless',
    name: 'Featherless AI',
    category: 'community',
    description: 'Run thousands of Hugging Face models instantly',
    apiBaseUrl: 'https://api.featherless.ai/v1',
    websiteUrl: 'https://featherless.ai',
    docsUrl: 'https://docs.featherless.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama/Meta-Llama-3-8B-Instruct']
  },
  {
    templateId: 'novita',
    name: 'Novita AI',
    category: 'community',
    description: 'Fast and reliable AI API',
    apiBaseUrl: 'https://api.novita.ai/v3/openai',
    websiteUrl: 'https://novita.ai',
    docsUrl: 'https://novita.ai/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama/llama-3-70b-instruct']
  },
  {
    templateId: 'hyperbolic',
    name: 'Hyperbolic AI',
    category: 'community',
    description: 'Open source AI compute platform',
    apiBaseUrl: 'https://api.hyperbolic.xyz/v1',
    websiteUrl: 'https://hyperbolic.xyz',
    docsUrl: 'https://docs.hyperbolic.xyz',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama/Meta-Llama-3-70B-Instruct']
  },
  {
    templateId: 'infermatic',
    name: 'Infermatic AI',
    category: 'community',
    description: 'High-performance AI model serving',
    apiBaseUrl: 'https://api.infermatic.ai/v1',
    websiteUrl: 'https://infermatic.ai',
    docsUrl: 'https://docs.infermatic.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama-3-70b-instruct']
  },
  {
    templateId: 'siliconflow',
    name: 'SiliconFlow',
    category: 'community',
    description: 'Inference platform for Chinese and global open models',
    apiBaseUrl: 'https://api.siliconflow.cn/v1',
    websiteUrl: 'https://siliconflow.cn',
    docsUrl: 'https://docs.siliconflow.cn',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['Qwen/Qwen2-72B-Instruct']
  },
  {
    templateId: 'friendliai',
    name: 'FriendliAI',
    category: 'community',
    description: 'High-performance generative AI serving',
    apiBaseUrl: 'https://inference.friendli.ai/v1',
    websiteUrl: 'https://friendli.ai',
    docsUrl: 'https://docs.friendli.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama-3-70b-instruct']
  },
  {
    templateId: 'lambda',
    name: 'Lambda AI',
    category: 'community',
    description: 'Lambda GPU cloud chat endpoints',
    apiBaseUrl: 'https://api.lambdalabs.com/v1',
    websiteUrl: 'https://lambdalabs.com',
    docsUrl: 'https://lambdalabs.com/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['llama-3-70b-instruct']
  },
  {
    templateId: 'runpod',
    name: 'RunPod Serverless',
    category: 'community',
    description: 'Serverless vLLM and custom API endpoints',
    apiBaseUrl: 'https://api.runpod.ai/v2/{endpoint_id}/openai/v1',
    websiteUrl: 'https://runpod.io',
    docsUrl: 'https://docs.runpod.io',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['runpod-custom-model']
  }
];
