import { ProviderTemplate } from './types';

export const officialTemplates: ProviderTemplate[] = [
  {
    templateId: 'openai',
    name: 'OpenAI',
    category: 'official',
    description: 'GPT-4o, GPT-4o Mini, o1 reasoning models',
    apiBaseUrl: 'https://api.openai.com/v1',
    websiteUrl: 'https://openai.com',
    docsUrl: 'https://platform.openai.com/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['gpt-4o', 'gpt-4o-mini', 'o1-preview', 'o1-mini'],
    capabilities: { chat: true, vision: true, toolCalling: true, jsonMode: true, reasoning: true, embeddings: true, imageGeneration: true, audio: true, maxContextTokens: 128000 }
  },
  {
    templateId: 'gemini',
    name: 'Google Gemini',
    category: 'official',
    description: 'Gemini 1.5 Pro, 1.5 Flash, 2.5 Flash',
    apiBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    websiteUrl: 'https://ai.google.dev',
    docsUrl: 'https://ai.google.dev/docs',
    authType: 'api-key-header',
    customHeaderName: 'x-goog-api-key',
    requiresApiKey: true,
    defaultModels: ['gemini-1.5-pro', 'gemini-1.5-flash', 'gemini-2.5-flash'],
    capabilities: { chat: true, vision: true, toolCalling: true, jsonMode: true, maxContextTokens: 2000000 }
  },
  {
    templateId: 'anthropic',
    name: 'Anthropic Claude',
    category: 'official',
    description: 'Claude 3.5 Sonnet, Haiku, Opus',
    apiBaseUrl: 'https://api.anthropic.com/v1',
    websiteUrl: 'https://anthropic.com',
    docsUrl: 'https://docs.anthropic.com',
    authType: 'custom-header',
    customHeaderName: 'x-api-key',
    requiresApiKey: true,
    defaultModels: ['claude-3-5-sonnet-latest', 'claude-3-haiku-20240307', 'claude-3-opus-20240229'],
    customHeaders: { 'anthropic-version': '2023-06-01' },
    capabilities: { chat: true, vision: true, toolCalling: true, maxContextTokens: 200000 }
  },
  {
    templateId: 'openrouter',
    name: 'OpenRouter',
    category: 'official',
    description: 'Router API to 100+ models (Claude 3.5, Llama 3, Mistral)',
    apiBaseUrl: 'https://openrouter.ai/api/v1',
    websiteUrl: 'https://openrouter.ai',
    docsUrl: 'https://openrouter.ai/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['anthropic/claude-3.5-sonnet', 'anthropic/claude-3-haiku', 'meta-llama/llama-3.1-405b-instruct'],
    capabilities: { chat: true, vision: true, toolCalling: true, jsonMode: true, maxContextTokens: 128000 }
  },
  {
    templateId: 'github_models',
    name: 'GitHub Models',
    category: 'official',
    description: 'Free multi-token LLM inference via GitHub Personal Access Tokens',
    apiBaseUrl: 'https://models.inference.ai.azure.com',
    websiteUrl: 'https://github.com/marketplace/models',
    docsUrl: 'https://github.com/marketplace/models',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['gpt-4o', 'Phi-3-medium-4k-instruct', 'Llama-3.1-70B-Instruct'],
    capabilities: { chat: true, vision: true, toolCalling: true, jsonMode: true, maxContextTokens: 128000 }
  },
  {
    templateId: 'azure_openai',
    name: 'Microsoft Azure OpenAI',
    category: 'official',
    description: 'Enterprise OpenAI API endpoints hosted on Azure',
    apiBaseUrl: 'https://{resource}.openai.azure.com/openai/deployments',
    websiteUrl: 'https://azure.microsoft.com/en-us/products/ai-services/openai-service',
    docsUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/openai/',
    authType: 'custom-header',
    customHeaderName: 'api-key',
    requiresApiKey: true,
    defaultModels: ['gpt-4o', 'gpt-4o-mini', 'text-embedding-3-small'],
    capabilities: { chat: true, vision: true, toolCalling: true, jsonMode: true, embeddings: true }
  },
  {
    templateId: 'groq',
    name: 'Groq',
    category: 'official',
    description: 'High-speed LPU inference for Llama 3.3 70B & Mixtral',
    apiBaseUrl: 'https://api.groq.com/openai/v1',
    websiteUrl: 'https://groq.com',
    docsUrl: 'https://console.groq.com/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['llama-3.3-70b-versatile', 'mixtral-8x7b-32768'],
    capabilities: { chat: true, toolCalling: true, jsonMode: true, streaming: true }
  },
  {
    templateId: 'together_ai',
    name: 'Together AI',
    category: 'official',
    description: 'Inference and fine-tuning platform for open-source models',
    apiBaseUrl: 'https://api.together.xyz/v1',
    websiteUrl: 'https://together.ai',
    docsUrl: 'https://docs.together.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama/Llama-3-70b-chat-hf', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
    capabilities: { chat: true, vision: true, toolCalling: true, jsonMode: true }
  },
  {
    templateId: 'deepinfra',
    name: 'DeepInfra',
    category: 'official',
    description: 'Serverless inference for open-source LLMs',
    apiBaseUrl: 'https://api.deepinfra.com/v1/openai',
    websiteUrl: 'https://deepinfra.com',
    docsUrl: 'https://deepinfra.com/docs',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama/Meta-Llama-3-70B-Instruct', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
    capabilities: { chat: true, toolCalling: true, jsonMode: true }
  },
  {
    templateId: 'fireworks',
    name: 'Fireworks AI',
    category: 'official',
    description: 'Fast and scalable inference platform for custom and open models',
    apiBaseUrl: 'https://api.fireworks.ai/inference/v1',
    websiteUrl: 'https://fireworks.ai',
    docsUrl: 'https://readme.fireworks.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['accounts/fireworks/models/llama-v3-70b-instruct', 'accounts/fireworks/models/mixtral-8x22b-instruct'],
    capabilities: { chat: true, toolCalling: true, jsonMode: true }
  },
  {
    templateId: 'cohere',
    name: 'Cohere',
    category: 'official',
    description: 'Enterprise AI platform offering Command R and Command R+',
    apiBaseUrl: 'https://api.cohere.ai/v1',
    websiteUrl: 'https://cohere.com',
    docsUrl: 'https://docs.cohere.com',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['command-r-plus', 'command-r', 'command-light'],
    capabilities: { chat: true, toolCalling: true, embeddings: true }
  },
  {
    templateId: 'mistral',
    name: 'Mistral AI',
    category: 'official',
    description: 'La Plateforme for Mistral Large, NeMo, and Pixtral',
    apiBaseUrl: 'https://api.mistral.ai/v1',
    websiteUrl: 'https://mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['mistral-large-latest', 'open-mistral-nemo', 'pixtral-12b-2409'],
    capabilities: { chat: true, vision: true, toolCalling: true, jsonMode: true }
  },
  {
    templateId: 'ai21',
    name: 'AI21 Labs',
    category: 'official',
    description: 'Jamba models and Wordtune API',
    apiBaseUrl: 'https://api.ai21.com/studio/v1',
    websiteUrl: 'https://ai21.com',
    docsUrl: 'https://docs.ai21.com',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['jamba-1.5-large', 'jamba-1.5-mini', 'j2-ultra'],
    capabilities: { chat: true }
  },
  {
    templateId: 'xai',
    name: 'xAI (Grok)',
    category: 'official',
    description: 'Grok API by xAI',
    apiBaseUrl: 'https://api.x.ai/v1',
    websiteUrl: 'https://x.ai',
    docsUrl: 'https://docs.x.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['grok-beta'],
    capabilities: { chat: true, vision: true, toolCalling: true, jsonMode: true }
  },
  {
    templateId: 'perplexity',
    name: 'Perplexity AI',
    category: 'official',
    description: 'Sonar online and offline models powered by Llama 3',
    apiBaseUrl: 'https://api.perplexity.ai',
    websiteUrl: 'https://perplexity.ai',
    docsUrl: 'https://docs.perplexity.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['llama-3.1-sonar-large-128k-online', 'llama-3.1-sonar-small-128k-online'],
    capabilities: { chat: true }
  },
  {
    templateId: 'sambanova',
    name: 'SambaNova',
    category: 'official',
    description: 'Fast Llama 3.3 and Samba-Coeur models',
    apiBaseUrl: 'https://api.sambanova.ai/v1',
    websiteUrl: 'https://sambanova.ai',
    docsUrl: 'https://docs.sambanova.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['Meta-Llama-3.3-70B-Instruct'],
    capabilities: { chat: true, toolCalling: true, jsonMode: true }
  },
  {
    templateId: 'cerebras',
    name: 'Cerebras',
    category: 'official',
    description: 'Extreme speed LLM inference on CS-3 hardware',
    apiBaseUrl: 'https://api.cerebras.ai/v1',
    websiteUrl: 'https://cerebras.ai',
    docsUrl: 'https://inference-docs.cerebras.ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['llama3.1-70b', 'llama3.1-8b'],
    capabilities: { chat: true }
  },
  {
    templateId: 'nvidia_nim',
    name: 'NVIDIA NIM',
    category: 'official',
    description: 'NVIDIA inference microservices API',
    apiBaseUrl: 'https://integrate.api.nvidia.com/v1',
    websiteUrl: 'https://build.nvidia.com',
    docsUrl: 'https://docs.api.nvidia.com',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta/llama-3.1-405b-instruct', 'nvidia/nemotron-4-340b-instruct'],
    capabilities: { chat: true, toolCalling: true, jsonMode: true }
  },
  {
    templateId: 'cloudflare',
    name: 'Cloudflare Workers AI',
    category: 'official',
    description: 'Serverless GPU inference at the edge',
    apiBaseUrl: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run',
    websiteUrl: 'https://developers.cloudflare.com/workers-ai',
    docsUrl: 'https://developers.cloudflare.com/workers-ai',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['@cf/meta/llama-3-8b-instruct'],
    capabilities: { chat: true }
  },
  {
    templateId: 'huggingface',
    name: 'Hugging Face Inference API',
    category: 'official',
    description: 'Serverless endpoints for Hugging Face models',
    apiBaseUrl: 'https://api-inference.huggingface.co/models',
    websiteUrl: 'https://huggingface.co',
    docsUrl: 'https://huggingface.co/docs/api-inference',
    authType: 'bearer',
    requiresApiKey: true,
    defaultModels: ['meta-llama/Meta-Llama-3-8B-Instruct'],
    capabilities: { chat: true }
  }
];
